import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import nextPlugin from '@next/eslint-plugin-next'
import reactHooks from 'eslint-plugin-react-hooks'
import comments from '@eslint-community/eslint-plugin-eslint-comments/configs'
import globals from 'globals'

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'src/payload-types.ts', // generated by `payload generate:types`
      'next-env.d.ts',
      'next.config.ts', // root config, not part of the src TS program
      'eslint.config.mjs',
    ],
  },

  js.configs.recommended,

  // Type-aware, maximum strictness.
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node, ...globals.browser },
    },
  },

  // Disallow eslint-disable of the rules below (see the house-rules block).
  comments.recommended,

  // Next.js + React hooks.
  {
    plugins: { '@next/next': nextPlugin, 'react-hooks': reactHooks },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  // House rules — the non-negotiable ones.
  {
    rules: {
      // Type assertions are forbidden. Only `as const` survives.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSTypeAssertion',
          message:
            'Type assertions (<T>x) are forbidden — use a type guard, proper types, or a Zod schema.',
        },
        {
          selector: "TSAsExpression:not(:has(> TSTypeReference[typeName.name='const']))",
          message:
            'Type assertions (`x as T`) are forbidden — use a type guard, proper types, or a Zod schema. Only `as const` is allowed.',
        },
      ],
      // Numbers in template literals are fine.
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      // Allow intentionally-unused identifiers prefixed with `_`.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      // No bypassing the type system.
      '@typescript-eslint/ban-ts-comment': 'error',
      // …and the assertion ban itself cannot be turned off inline.
      '@eslint-community/eslint-comments/no-restricted-disable': [
        'error',
        'no-restricted-syntax',
        '@typescript-eslint/ban-ts-comment',
      ],
      '@eslint-community/eslint-comments/no-unlimited-disable': 'error',
    },
  },

  // Config / plain-JS files: no type-aware linting (not part of the TS program).
  {
    files: ['**/*.{js,mjs,cjs}'],
    ...tseslint.configs.disableTypeChecked,
  },

  // Seed/CLI scripts may log to the console.
  {
    files: ['src/scripts/**'],
    rules: { 'no-console': 'off' },
  },
)
